### ISSUE TITLE
Failing paypal requests

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/eas-backend#268]
```
[20241213 10:24:38.402] INFO eas.api.views:views.paypal_accept | Accepting payment for id 'PAYID-M5OAWHQ5014683877857222E' and payer 'YUWS2BAMSM56A'
[20241213 10:24:38.402] INFO eas.api.views:views.paypal_accept | Accepting payment for id 'PAYID-M5OAWHQ5014683877857222E' and payer 'YUWS2BAMSM56A'
[20241213 10:24:38.411] INFO paypalrestsdk.api:api.http_call | Request[POST]: https://api.paypal.com/v1/oauth2/token
[20241213 10:24:38.411] INFO paypalrestsdk.api:api.http_call | Not logging full request/response headers and body in live mode for compliance
[20241213 10:24:38.689] INFO paypalrestsdk.api:api.http_call | Response[200]: OK, Duration: 0.277654s.
[20241213 10:24:38.689] INFO paypalrestsdk.api:api.http_call | Request[GET]: https://api.paypal.com/v1/payments/payment/PAYID-M5OAWHQ5014683877857222E
[20241213 10:24:38.689] INFO paypalrestsdk.api:api.http_call | Not logging full request/response headers and body in live mode for compliance
[20241213 10:24:39.013] INFO paypalrestsdk.api:api.http_call | Response[200]: OK, Duration: 0.323523s.
[20241213 10:24:39.014] INFO paypalrestsdk.api:api.request | PayPal-Request-Id: 8a2e978b-cacf-4948-8f29-1c443c616731
[20241213 10:24:39.014] INFO paypalrestsdk.api:api.http_call | Request[POST]: https://api.paypal.com/v1/payments/payment/PAYID-M5OAWHQ5014683877857222E/execute
[20241213 10:24:39.014] INFO paypalrestsdk.api:api.http_call | Not logging full request/response headers and body in live mode for compliance
[20241213 10:24:40.357] INFO paypalrestsdk.api:api.http_call | Response[400]: Bad Request, Duration: 1.342906s.
[20241213 10:24:40.357] ERROR eas.api.paypal:paypal.accept_payment | {'name': 'INSTRUMENT_DECLINED', 'message': "The instrument presented was either declined by the processor or bank, or it can't be used for this payment.", 'information_link': 'https://developer.paypal.com/docs/api/payments/#errors', 'debug_id': 'ac4bcde956191'}
[20241213 10:24:40.357] ERROR eas.api.paypal:paypal.accept_payment | {'name': 'INSTRUMENT_DECLINED', 'message': "The instrument presented was either declined by the processor or bank, or it can't be used for this payment.", 'information_link': 'https://developer.paypal.com/docs/api/payments/#errors', 'debug_id': 'ac4bcde956191'}
[20241213 10:24:40.358] ERROR django.request:log.log_response | Internal Server Error: /api/paypal/accept/
Traceback (most recent call last):
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/echaloasuerte-3/venv/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/var/www/echaloasuerte-3/web-app/./eas/api/views.py", line 393, in paypal_accept
    paypal.accept_payment(payment_id, payer_id)
  File "/var/www/echaloasuerte-3/web-app/./eas/api/paypal.py", line 62, in accept_payment
    raise Exception("Failed to process PayPal Payment")
Exception: Failed to process PayPal Payment
```

**Comment by mariocj89** [comment]
Fixed
